/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cipher;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        Cipher cipher = new Cipher();

        do {
            System.out.println("Enter plaintext: ");
            String plaintext = scanner.nextLine();

            if (plaintext.equals("exit")) {
                break;
            }

            System.out.println("Encoded:\n" + cipher.encode(plaintext));
            System.out.println("Decoded:\n" + cipher.decode(plaintext));
        } while (true);

        scanner.close();
    }
}
